name: Render paper.pdf
on: 
  workflow_dispatch:
  push:
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: typst-community/setup-typst@v5
      # 🎉 Now Typst is installed!
      - run: typst compile src/stelf.typ main.pdf
