name: Render paper.pdf
on: 
  workflow_dispatch:
  push:
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: typst-community/setup-typst@v5
      # 🎉 Now Typst is installed!
      - run: typst compile src/stelf.typ main.pdf
      - run: typst compile --features html src/stelf.typ main.html
      - uses: actions/upload-artifact@v6
        with:
          name: book
          path: main.pdf
      - uses: actions/upload-artifact@v6
        with:
          name: page 
          path: main.html
