name: Render paper.pdf
on: 
  workflow_dispatch:
  push:
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: typst-community/setup-typst@v5
      # 🎉 Now Typst is installed!
      - run: typst compile src/stelf.typ main.pdf
      - uses: SichangHe/pdf2htmlEX-action@v0.0.2
        with:
          arguments: main.pdf main.html
      - uses: actions/upload-artifact@v6
        with:
          name: book
          path: main.pdf
      - uses: actions/upload-artifact@v6
        with:
          name: page 
          path: main.html
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
